# Mode
debug : False
device : 'cuda:2'

# Dataset
image_path : '/media/data/trung/deep/data/images-fold1/' # forder alll image    # phải có / ở cuối 
train_path : 'fold_1_train.csv' # file csv
valid_path : 'fold_1_test.csv'   # file csv
batch_size : 64
num_workers : 8
output_path : 'output/'  # phải có / ở cuối 
max_epoch : 20

# Checkpoint
continue_train : false
checkpoint_path : 'output-freeze/model_10.pt' # tiếp tục train thì nhớ thêm vào


# Optimizer
lr : 0.001

# Transform
image_size : (137, 236) # nếu train với size gốc phải để crop = False

crop : False
padding : 16

use_cutout : True
cutmix_ratio : 1
cutmix_bien : 0.5

auto_aug : True